import 'package:get/get.dart';

class MyLocal implements Translations {
  @override

  Map<String, Map<String, String>> get keys => {
    'ar' : {
      '1' : 'تسجيل الدخول',
      '2' : 'إنشاء حساب',
      '3' : 'الاستمرار ك ضيف',
      '4' : 'أدخل الإيميل',
      '5' : 'أدخل كلمة السر',
      '6' : 'الإيميل',
      '7' : 'كلمة السر',
      '8' : 'الأسئلة الشائعة',
      '9' : 'كيف يمكنني فتح حساب؟',
      '10' : 'لفتح حساب بنكي لدينا يتوجب عليك التوجه إلى إحدى فروعنا وطلب التحدث مع ممثلي خدمة العملاء وسيكونون سعيدين بمساعدتك, لا تنس إحضار بطاقة الهوية الخاصة بك.',
      '11' : 'ما هي الأوراق الثبوتية المطلوبة لفتح حساب مصرفي؟',
      '12' : 'لفتح حساب مصرفي, كل ما تحتاجه هو الهوية الشخصية.',
      '13' : 'كم عدد فروع بنك سوريا الإسلامي؟',
      '14' : 'بنك سوريا الإسلامي لديه ثلاث فروع ضمن العاصمة دمشق في العناوين التالية:  الفرع الرئيسي: المزة أتوستراد - مقابل ملعب الجلاء, فرع 2: أبو رمانة - مقابل وزارة النقل, فرع 3: مشروع دمر - جانب الأب تاون.  ',
      '15' : 'ما هو رقم خدمة العملاء؟',
      '16' : 'للتواصل مع فريق خدمة العملاء، اتصل بنا على الرقم 011-6121525',
      '17' : 'ما هو الحد الأدنى للرصيد المطلوب لفتح حساب؟',
      '18' : 'يتطلب مبلغ بقيمة 5000 ل.س فقط لفتح حساب.',
      '19' : 'ما هو الحد الأعلى للسحب من أجهزة الصراف الآلي؟',
      '20' : 'يمكنك تحديد الحد الأعلى للسحب عند فتح الحساب بما لا بتعدى 500,000 ليرة سورية في اليوم.',
      '21' : 'تأكيد الخروج',
      '22' : 'هل ترغب في تسجيل الخروج؟',
      '23' : 'لا',
      '24' : 'نعم',
      '25' : 'هل ترغب في إغلاق التطبيق؟',
      '26' : 'تغيير اللغة',
      '27' : 'تأكيد الخروج',
      '28' : 'الايميل أو كلمة السر غير صحيحة',
      '29' : 'تم تسجيل الخروج',
      '30' : 'الأسئلة المساعدة',
      '31' : 'مرحبا',
      '32' : 'الايميل غير صحيح',
      '33' : 'كم رصيدي',
      '34' : '',
      '35' : '',

    },
    'en' : {
      '1' : 'Log In',
      '2' : 'Sign Up',
      '3' : 'Continue as a guest',
      '4' : 'Enter your Email',
      '5' : 'Enter your password',
      '6' : 'Email',
      '7' : 'Password',
      '8' : 'Frequently Asked Questions',
      '9' : 'How can I open an account?',
      '10' : 'To open a bank account with us, you must go to one of our branches and ask to speak with our customer service representatives. They will be happy to help you. Do not forget to bring your ID card.',
      '11' : 'What documents are required to open a bank account?',
      '12' : 'To open a bank account, all you need is a personal ID.',
      '13' : 'How many branches does IS Bank have?',
      '14' : 'IS Bank has three branches in Damascus, at the following addresses: Main Branch: Mezzeh Highway - opposite Al-Jalaa Stadium, Branch 2: Abu Rummaneh - opposite the Ministry of Transport, Branch 3: Dummar Project - next to UpTown.',
      '15' : 'What is your customer service number?',
      '16' : 'To contact our customer service team, call us on 011-6121525.',
      '17' : 'What is the minimum balance required to open an account?',
      '18' : 'Only 5000 SYP is required to open an account.',
      '19' : 'What is the maximum withdrawal limit from ATMs?',
      '20' : 'You can set the maximum withdrawal limit when opening the account, not to exceed 500,000 Syrian pounds per day.',
      '21' : 'confirm logging out',
      '22' : 'Do you want to log out?',
      '23' : 'No',
      '24' : 'Yes',
      '25' : 'Do you want to close the application?',
      '26' : 'Change Lanuage',
      '27' : 'Confirm closing',
      '28' : 'Your email or password is incorrect',
      '29' : 'You are logged out',
      '30' : 'Questions',
      '31' : 'Hello',
      '32' : 'Email is not valid',
      '33' : 'How much my balance',
      '34' : '',
      '35' : '',

    }
  };
}
